name: Update Gradle wrapper

on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup
        run: bash setup.sh
      - name: Dump Firmware
        run: bash test.sh
        env:
          MY_TOKEN: '${{ secrets.MY_TOKEN }}'
          TG_CHAT: '${{ secrets.TG_TOKEN }}'
          TG_CHAT: '${{ secrets.TG_CHAT }}'
